Update CouchDBClient.php
doctrine/couchdb-client pull request #94
Opened 2020-07-28 22:45 UTC by vlad88sv

On clustered CouchDB servers deleting a DB may return 202 - Accepted: Request has been accepted, but the corresponding operation may not have completed.

Reference: https://docs.couchdb.org/en/stable/api/basics.html#http-status-codes

2020-07-29 20:39 UTC, SenseException requested changes

2020-07-29 20:39 UTC, SenseException commented on lib/Doctrine/CouchDB/CouchDBClient.php
> +        if (!(in_array($response->status, [200,202,404]))) {
```suggestion
        if (! in_array($response->status, [200,202,404])) {
```

2020-07-30 15:00 UTC, vlad88sv commented
Thank you for your review @SenseException, please let me know if I need to add/fix anything else to get this accepted/merged.

I depend on this library for a production system and I would like to continue using the official version instead of a fork.

2020-07-31 19:09 UTC, SenseException commented
I'm not familiar with couchdb-client and if you need to target the `release/1.0.0` branch. Does anyone of @doctrine/team-couchdb can tell?

2022-09-27 22:08 UTC, closed without merging